In [14]:
import numpy as np

path6 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-30 21:53:00.679400 dpp_N:5 dpp_nu:20 dpp_rho3iter9999delta_mu0.6.npy"
path7 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-30 22:53:11.194727 dpp_N:5 dpp_nu:20 dpp_rho3iter9999delta_mu0.7.npy"
path8 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-31 00:14:41.896639 dpp_N:5 dpp_nu:20 dpp_rho3iter9999delta_mu0.8.npy"
path9 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-31 00:57:38.289635 dpp_N:5 dpp_nu:20 dpp_rho3iter9999delta_mu0.9.npy"
path10 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-31 01:56:51.741528 dpp_N:5 dpp_nu:20 dpp_rho3iter9999delta_mu1.npy"

path6_999 = "/media/disk1/chatgpt/aaapointprocess/mcmcbmm/npy/2023-12-30 10:50:56.951197 dpp_N:5 dpp_nu:20 dpp_rho3iter999delta_mu0.6.npy"


In [5]:
load_dict6 = np.load(path6, allow_pickle=True).item()
load_dict7 = np.load(path7, allow_pickle=True).item()
load_dict8 = np.load(path8, allow_pickle=True).item()
load_dict9 = np.load(path9, allow_pickle=True).item()
load_dict10 = np.load(path10, allow_pickle=True).item()

In [15]:
load_dict6_999 = np.load(path6_999, allow_pickle=True).item()

In [16]:
load_dict6_999[']

[[array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [array([0.26607909, 0.34454057, 0.32928503]),
  array([0.67106414, 0.63630515, 0.73519183]),
  array([0.75087973, 0.69864035, 0.70441783])],
 [arra

In [13]:
load_dict6['a_means']

[[array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [array([0.30121794, 0.34594608, 0.35682903]),
  array([0.62736294, 0.6448595 , 0.67247723]),
  array([0.76867957, 0.73511533, 0.73056313])],
 [arra